name       : libmediaart
version    : 1.9.5
release    : 13
source     :
    - https://download.gnome.org/sources/libmediaart/1.9/libmediaart-1.9.5.tar.xz : 07def5a42c482ae71d3e1f77a4d0fdc337f74226059a65284d6d5a241f0e9cd6
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Media Art library
description: |
    Media Art library
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - vala
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure -Dwith-docs=no
build      : |
    export LC_ALL=en_US.utf8
    %ninja_build
install    : |
    export LC_ALL=en_US.utf8
    %ninja_install
