name       : libmediaart
version    : 1.9.1
release    : 4
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libmediaart/1.9/libmediaart-1.9.1.tar.xz : 5b14aa4e0cc84eaec57b6cb28f39092d503fdaecf36d5d165fac37583b7fe949
license    : GPL-2.0
component  : desktop.gnome.core
summary    : Media Art library
description: |
    Media Art library
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
