name       : libmediaart
version    : 1.9.0
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libmediaart/1.9/libmediaart-1.9.0.tar.xz : 94668adb29d4dc3115b0fd105942ebd5ca6f5f9dbb2afa8a191a73a747dd506f
license    : GPL-2.0+
summary    : Media Art library
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - vala
description: |
    Media Art library
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
