name       : libmediaart
version    : 1.9.6
release    : 14
source     :
    - https://download.gnome.org/sources/libmediaart/1.9/libmediaart-1.9.6.tar.xz : c3bc5025d7db380587f9c8eb800c611f6b5a16d6b4b78fcff93f62876a677f17
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Media Art library
description: |
    Media Art library
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - vala
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure -Dgtk_doc=false
build      : |
    export LC_ALL=en_US.utf8
    %ninja_build
install    : |
    export LC_ALL=en_US.utf8
    %ninja_install
